name = "simple_bw"
description = "A simple, responsive theme for Zola SSG"
license = "MIT"
homepage = "https://github.com/bobbit6k/simple_bw"
min_version = "0.4.0"

[author]
name = "Roberto Berneri"
homepage = "https://robertoberneri.com"

[extra]
# Any default theme settings that should be available to users
